import { cookies } from "next/headers";

import { default_config } from "@/constants";

import { Type_Lang_Model } from "@/constants/types";

// providers like -> redux, react query
import Providers from "./Providers";

import { ToastContainer } from "react-toastify";

// toastify library
import "react-toastify/dist/ReactToastify.css";

// global css file
import "./style/globals.css";

// metadata
export const metadata = {
  title: "Nextjs Structure",
  description: "Nextjs Structure Generated by create next app",
};

export function getLang() {
  const cookieStore = cookies();

  // get language
  const cookiesGetLang = cookieStore.has("lang")
    ? cookieStore.get("lang")
    : undefined;

  const langOptions: Type_Lang_Model = cookiesGetLang
    ? JSON.parse(cookiesGetLang.value)
    : default_config.default_lang;

  return langOptions;
}

export function getTheme() {
  const cookieStore = cookies();

  // get theme
  const cookiesGetTheme = cookieStore.has("theme")
    ? cookieStore.get("theme")
    : undefined;

  const themeOptions: string = cookiesGetTheme
    ? cookiesGetTheme.value
    : default_config.default_theme;

  return themeOptions;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const langOptions = getLang();

  const themeOptions = getTheme();

  return (
    <html
      lang={langOptions.lang}
      dir={langOptions.dir}
      data-theme={themeOptions}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"
        />
      </head>
      <body>
        <Providers>{children}</Providers>
        {/* library for toast  */}
        <ToastContainer />
        {/* for modals  */}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
